import logging
from backend.agents.base_agent import BaseAgent
from backend.services.github_service import github_service

class PRAgent(BaseAgent):
    """
    Creates the DRAFT Pull Request on GitHub and notifies the user for approval.
    """
    
    async def run(self, state: dict) -> dict:
        self.logger.info("PRAgent generating draft pull request...")
        state["current_step"] = "creating_pr"
        
        # In reality, we would use git_tool to branch, commit, and push the code
        # then use github_service to open the PR.
        
        plan = state.get("engineering_plan", {}).get("markdown_content", "No plan available.")
        review = state.get("review_comments", {}).get("review_summary", "No AI review notes.")
        issue_id = state.get("issue_id")
        
        pr_title = f"AI Fix: Issue {issue_id}"
        pr_body = f"""## AI Generated Draft PR

This pull request was automatically generated by the OpenSource AI Engineer.

### Implementation Plan Summary
{plan[:500]}... [Truncated]

### AI Security & Performance Review
{review}

**STATUS: WAITING FOR HUMAN APPROVAL**
Please review this draft PR before marking it as Ready for Review.
        """
        
        # MOCK IMPLEMENTATION: We don't actually hit GitHub yet since we are in dev setup
        # pr_obj = github_service.create_draft_pr(...)
        
        pr_url = f"https://github.com/mock-repo/pulls/mock-123"
        
        state["pr_details"] = {
            "title": pr_title,
            "url": pr_url,
            "status": "draft",
            "body": pr_body
        }
        
        # LangGraph will interrupt here waiting for user approval.
        self.logger.info(f"Draft PR created at {pr_url}. Waiting for human approval.")
        
        return state
